[lib]
path = "src/_lib.rs"

[package]
name = "repr_c"
version = "0.1.0"
authors = ["Daniel Henry-Mantilla <daniel.henry.mantilla@gmail.com>"]
edition = "2018"

description = "#[repr(C)] equivalents of stdlib pervasive types for easier FFI"
license = "MIT"

[target.'cfg(not(target = "wasm32-unknown-unknown"))'.dependencies]
libc = { version = "0.2.66", default-features = false }

[features]
default = ["std", "derives"]

alloc = []
proc_macros = []
derives = [ "proc_macros" ]  # alias
headers = ["std"]
nightly = []
std = ["alloc", "log"]

[dev-dependencies]
macro_rules_attribute = "0.0.1"

[workspace]
members = ["src/proc_macro"]

[dependencies]
paste = "0.1.7"
_mod = { path = "../dhm/_mod" }
log = { version = "0.4.8", optional = true }

[dependencies.proc_macro]
package = "repr_c-proc_macro"
path = "src/proc_macro"
version = "0.1.0"
