[lib]
path = "mod.rs"
proc-macro = true

[package]
name = "repr_c-proc_macro"
version = "0.1.0"
authors = ["Daniel Henry-Mantilla <daniel.henry.mantilla@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = { version = "1.0", optional = true }
quote = { version = "1.0", optional = true }
syn = { version = "1.0", features = ["full"], optional = true }

[features]
headers = []
proc_macros = ["proc-macro2", "quote", "syn"]
verbose-expansions = []
