[lib]
crate-type = ["rlib", "staticlib"]

[package]
name = "ffi_tests"
version = "0.1.0"
authors = ["Daniel Henry-Mantilla <daniel.henry.mantilla@gmail.com>"]
edition = "2018"

[dependencies]
repr_c = { path = "..", features = ["proc_macros"] }

[features]
generate-headers = ["repr_c/headers"]

# [dev-dependencies]
# cc = "1.0.50"

[profile.dev]
panic = "unwind"
