[book]
title = "`safer_ffi` User Guide"
guide = "A guide to learn how to use the `::safer_ffi` FFI framework"
authors = ["Daniel Henry-Mantilla"]
language = "en"
multilingual = false
src = "src"

[output.html]
theme = "theme"
additional-css = ["theme/book.css"]
fold = { enable = true, level = 5 }
